nodejs/llnode

- src/llscan.cc
This is for issue #27 .
I noticed it while working on adding the findrefs command but wanted to keep this separate from those changes as it alters the behaviour of findjsobjects. (It's useful for findrefs because you may want to identify what is referring to a particular string.)
> Add strings to the histogram of objects on the heap.

- src/llnode.cc
- src/llscan.cc
- src/llscan.h
- src/llv8.cc
- src/llv8.h
This PR adds a findrefs command to llnode to allow a user to search for all references to an object.
At the moment it’s just scanning the same set of objects that findjsobjects and findjsinstances use. That might miss references from v8 internals but does limit the results to things a JavaScript programmer has direct control over. That may need to change later on.
I’ve got a blog posting explaining the command ready to go, I’ll update it before posting with any feedback and changes to the command. I’ll also do an update to the v8 usage in README.md afterwards just to reflect the current contents of the help but the number of commands is starting to build up a bit. Would it be worth discussing (under a separate issue) about where in the project is the right place to put some more …
> Add v8 findrefs command

- README.md
- src/llnode.cc
- src/llscan.cc
- src/llscan.h
- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
- test/fixtures/inspect-scenario.js
- test/inspect-test.js
This adds the option to display the full source associated with any function object via a --print-source (-s) flag when running v8 inspect. I think the choice of flag name makes sense but I'm happy to change it.
Some sample output is below. I'm happy to change the format of the output, though I can't do much about the formatting on the code that's being displayed. :-)
Sample output:
(lldb) v8 inspect --print-source 0x000022689a088939
0x000022689a088939:<function: helloworld at callfunctions.js:13:20
context=0x000022689a0888a9
source:
function helloworld() {
console.log("Hello World!");
}
>
> Add —-print-source (-s) flag

- README.md
The current version of README.md lists 3 commands. There are now 8 and more options to some of the commands, we should update it.
> Update output of v8 help in README.md

- src/llv8.cc
There shouldn't ever be a string with negative length but v8 could have been doing anything when the core dump was created and something catastrophic may have caused the core dump in the first place. Also because we scan all of memory looking for things that might be objects we may hit something that looked a bit like a string but wasn't really.
This fixes an issue I hit while working with a random test dump. That dump was created with --abort_on_uncaught_exception so this may well be frequent enough happen to someone else as well.
> llv8.cc - Guard against obviously invalid string lengths.

- src/llnode.cc
Fix up the arguments array to contain a first element rather than
subtract 1 from the lldb arguments and pretend they start at
args[1].
Linux prints args[0] in it's error message so it must point to a real
array element.
(Mac OSX appears to be hardcoded to use the program name in argv[0]
and ignores the first element of the arguments array.)
Fixes #41
> llnode.cc: Fix linux options parsing crash.

- src/llnode.cc
- src/llscan.cc
- src/llscan.h
- src/llv8.cc
This change adds a -n <name> option to v8 findrefs to search for all references referred to from properties named <name>. It also adds a -v option that matches the current (and still default with no flag specified) behaviour where all references to a property with that value are returned.
When findrefs was added ( https://github.com/nodejs/llnode/pull/32 ) I refactored it’s code as part of the review so that it could be easily extended. This enhancement takes advantage of that.
The output is the same as findrefs <object address> so the user sees the referring object address, it’s type, the field name and the object referred to from that property. Effectively it is scanning for all objects that contain a property with a particular name but the output is quite concise and allows the user to …
> Add findrefs -n to search by property name

- src/llv8-constants.cc
I hit an issue using llnode with the latest master branch of lldb. It couldn't read any of the values for the constants from Linux core dumps.
It turns out that up to lldb 3.9 GetLoadAddress and GetFileAddress return the same value. In the current master branch of lldb they seem to return different values on Linux and GetFileAddress returns the one we should read to obtain the symbol value. (On Mac they always seem to return the same value.)
The only discussion I can find on the differences between a file address and load address are in an lldb review request for updating the documentation: https://reviews.llvm.org/D22831
based on that I think we should be using file address if we want to read that memory address later.
I've checked the fix on the default Mac lldb, lldb 3.9 on Linux and …
> llv8-constants: Use file address for symbol lookup

- src/llnode.cc
- src/llscan.cc
- src/llscan.h
This PR adds the ability to search for a property where the value is a given javascript string. It functions much the same as the search for a value by id (address) but will match any JavaScript string that is equal to the string passed on the command line. This means it can potentially match more than one JavaScript object.
Luckily the lldb command line interpreter takes care of handling quoted strings. All I’ve added is a check for extra parameters when someone should have quoted a string.
> Add findrefs -s flag to search by property

- src/llnode.cc
Since we are starting to see people using lldb 3.9 in the field (at least on Linux) this just makes sure they don't see confusing help messages that don't apply since 3.9 has the SBMemoryRegionInfoList API available.
> llnode.cc: Only mention ranges file if it is needed.

- README.md
With the awesome https://github.com/nodejs/llnode/pull/60 now it's possible to install llnode with npm, but the README is not updated so https://www.npmjs.com/package/llnode looks a bit confusing at the moment.
This PR:
* Include instructions on installation with npm.
* Also update the output of `help v8`.
> readme: include npm install instructions

- scripts/configure.js
The default version of lldb on MacOS now contains the
SBMemoryRegionInfo API allowing us to scan the heap without
using the scripts to generate a segments file.
This simplifies the use of llnode as the v8 find* commands
are now automatically available to the user.
> configure.js: Update lldb header downloads.

- gyp_llnode
cc -dumpversion only reports 7 (not 7.0) on gcc 7, this confuses
the code that expects a two digit version.
This patch just makes sure the version number is padded to at least
two digits so 7 will report 7.0.
> Fix issue with gcc 7 confusing gyp_llnode

- src/llscan.cc
- src/llscan.h
- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- test/scan-test.js
This depends on changes that haven't been upstreamed yet.  Diff for the eager:
```diff
diff --git a/deps/v8/tools/gen-postmortem-metadata.py b/deps/v8/tools/gen-postmortem-metadata.py
index 8857134..8f8d8a1 100644
--- a/deps/v8/tools/gen-postmortem-metadata.py
+++ b/deps/v8/tools/gen-postmortem-metadata.py
@@ -99,6 +99,22 @@ consts_misc = [
'value': 'kAccessor' },
{ 'name': 'prop_kind_mask',
'value': 'PropertyDetails::KindField::kMask' },
+    { 'name': 'prop_location_Descriptor',
+        'value': 'kDescriptor' },
+    { 'name': 'prop_location_Field',
+        'value': 'kField' },
+    { 'name': 'prop_location_mask',
+        'value': 'PropertyDetails::LocationField::kMask' },
+    { 'name': 'prop_location_shift',
+        'value': 'PropertyDetails::LocationField::kShift' },
+    { …
```
> src,test: support node.js >= 8

- src/llv8.cc
- src/llv8.h
On 64 bits systems, V8 stores SMIs (small ints) in the top 32 bits
of a 64 bits word.  Frame markers used to obey this convention but
as of V8 5.8, they are stored as 32 bits SMIs with the top half set
to zero.  Shift the raw value up to make it a normal SMI again.
Fixes test/frame-test.js with the latest node.js v8.0.0-pre, it was
no longer able to detect special JS stack frames like entry and exit
frames, argument adapter frames, etc.
> src: support V8 5.8 stack frame markers

- README.md
Make it clearer how a core dump should be loaded so llnode can obtain all the debug information it needs. I've added the docs to the linux section as (I think) the MacOS core dump actually the executable binaries.
This is for issue #74
> README.md: Improve core dump loading instructions

- src/llnode.cc
- src/llscan.cc
- test/common.js
- test/usage-test.js
This commit prevents a segfault on `v8 print`.
I'll be adding a test as well, but it requires some changes to `test/common.js` first.
> src: don't crash with no arguments to print

- src/llnode.cc
- src/llv8.cc
- src/llv8.h
- test/fixtures/inspect-scenario.js
- test/inspect-test.js
Also added tests for `--string-length` since they are pretty similar...
Refs: https://github.com/nodejs/llnode/issues/89
cc:/ @bnoordhuis
> src: implement `v8 inspect --array-length` for large arrays

- src/llnode.cc
- src/llscan.cc
- src/llv8-constants.cc
- src/llv8.cc
- test/frame-test.js
- test/scan-test.js
Previously, `v8 bt` would exclude frames that didn't map to a C++ symbol
or a JS stack frame.  llnode does not currently know how to identify the
stack frames of V8 builtins so those were omitted as well.
This commit makes those stack frames visible and introduces a heuristic
(in lldb >= 3.9) where frames whose PC is inside a WX memory segment are
assumed to belong to V8 builtins.
Fixes: #99
First commit is cleanup, second commit fixes a test, third one is the fix for #99.
> src: print builtins and unnamed stack frames

- src/llscan.cc
Missed llscan.cc, cc @hhellyer.
> src: fix build error with lldb 3.8

- scripts/configure.js
- src/llnode.cc
It looks like the travis CI build does an npm install in a git checkout.
I've tested that locally and it fails due to some of the directories already existing. This PR tries to fix that and also means that running npm install in a local git clone should work.
I think travis will build PR's automatically so I may add changes if this does not resolve the issue.
> Allow npm install to work in git clone.

- README.md
- package.json
- scripts/configure.js
- scripts/llnode.sh
Since @No9 fixed global installation it's more practical to add an llnode command using a `bin` entry in package.json. This is a work in progress PR to get some feedback on whether anyone else thinks it's a good idea.
This implementation is fairly simple, it just wrappers lldb and pre-loads the plugin. (It also changes the prompt so you know it's worked.) Any other argument is just passed straight through so all the existing lldb options can be passed.
This allows the debug workflows:
`$ npm install -g llnode`
followed by:
`$ llnode node -c core` for postmortem debugging.
or
`$ llnode -- node --abort_on_uncaught_exception test.js` for JavaScript debug.
or
`$ llnode -- node test_for_crashing_native_npm.js` for crashes when developing npm modules containing native code.
(There are probably …
> Add an llnode command script that invokes lldb with the plugin loaded.

- src/llscan.cc
- src/llscan.h
With those changes, llscan will keep a cache of searched references and
will use this cache to avoid rescanning the entire heap each time.
This will improve performance when executing findrefs multiple times.
Fixes: https://github.com/nodejs/llnode/issues/97
> Improved findrefs execution speed after it runs the first time

- README.md
- package.json
- scripts/configure.js
This is a patch to enable llnode to work on freebsd from an npm install. 
I think most of the code and docs are pretty straight forward.
It imitates the linux approach currently in place. 
I have intentionally not modified the linux path through the code to make it easy to reason about. 
I am not to sure about the package.json line as it looks verbose 
https://github.com/nodejs/llnode/compare/master...No9:freebsd-install?expand=1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12 
Maybe this should go in its own script now?
> Freebsd Install

- src/llv8.cc
- src/llv8.h
- test/fixtures/inspect-scenario.js
- test/inspect-test.js
This PR adds support for reading contents from array buffers, typed arrays, and Node buffers (since they are Uint8Arrays).
This currently prints the content like this:
```
(lldb) v8 inspect 0x00000c20705a94c9
0x00000c20705a94c9:<Object: Object elements {
[0]=0x00003ea02c904211:<null>,
[4]=0x00003ea02c904241:<undefined>,
[23]=0x00000c20705aa9a1:<JSRegExp source=/regexp/>,
[25]=0x00001a9002c04cb1:<function: c.hashmap.(anonymous function) at /Users/joyee/projects/llnode/test/fixtures/inspect-scenario.js:40:19>}
properties {
.some-key=<Smi: 42>,
.other-key=0x000002ecfb6c8379:<String: "ohai">,
.cons-string=0x00000c20705a9669:<String: "this could be a ...">,
.array=0x00000c20705a96f1:<Array: length=6>,
.long-array=0x00000c20705a97e1:<Array: length=20>, …
```
> src, test: support reading contents from buffers

- src/llnode.cc
- src/llscan.cc
- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
- test/fixtures/inspect-scenario.js
- test/frame-test.js
- test/inspect-test.js
Fixes: https://github.com/nodejs/llnode/issues/117
In Node.js v8.3.0 Turbofan has been enabled by default, so thin strings have also been enabled and now Turbofan would put stub frames on the stack (to store register states for bytecode handlers, I think).
Before this change, when viewing the backtrace of `test/fixtures/inspect-scenario.js` with Node.js v8.3.0, frames containing functions with thin string arguments or in thin string paths would be broken:
<details><summary>See backtrace of inspect-scenario.js</summary>
```
* thread #1: tid = 0x81d450, 0x0000000100bbe942 node`v8::base::OS::Abort() at platform-posix.cc:261, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
* frame #0: 0x0000000100bbe942 node`v8::base::OS::Abort() at …
```
> src: support thin strings and stub frames

- README.md
- src/llnode.cc
- src/llv8.cc
- src/llv8.h
When I reviewed PR #116 for @joyeecheung I noticed that we have separate length arguments to v8 inspect for Strings and Arrays when we can only be inspecting one or the other. This PR merges the two into `--length` as they can never both apply at the same time. It also supports a short option, `-l`, to the user quickly specify how many elements of either strings or arrays to display. The major usability improvement is that you can just specify `-l` instead of having to type out `--array-length` or `--string-length`.
I did consider using `--count` and `-c` instead and I'm happy to swap around if anyone thinks that's better.
> llnode.cc: Combine array-length and string-length arguments

- src/llnode.cc
- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
- test/inspect-test.js
This is still a work in progress, but adds postmortem debugging support for V8 6.1. The following issues still need to be resolved (all marked with `TODO` in the code):
UPDATE: The issue with the `Uint8Array`s is that the backing stores are not materialized. If the test is updated to reference the `.buffer` property, the backing store is materialized and shows up properly in llnode.
> src,test: support V8 6.1 postmortem data

- src/llv8-inl.h
- test/common.js
- test/fixtures/inspect-scenario.js
- test/inspect-test.js
Sliced strings with an external string as a parent would use their offset and length values against the string "(external)" as support for external strings is not implemented yet.
This may resolve issue #112 as I see a crash in the same way without this fix however a crash in the inspect code for another type would manifest in the same way. I will ask @gentlejo to check if this resolves the problem for them.
> llv8-inl.h: Fix crash on sliced external strings

- scripts/configure.js
This change removes the hardcoded map of lldb versions to release branches. This makes it easier to use the --lldb_exe= parameter to handle unknown releases should find the correct branch for pre-release lldb builds or local builds of lldb.
It also makes the the installer aware of lldb-5.0 binaries on Linux since pre-release versions can be installed directly from llvm.org, see: http://apt.llvm.org/
This fixes issue #133
> configure.js: Simplify lldb version handling

- README.md
- package.json
- scripts/configure.js
- src/llnode.cc
- src/llscan.cc
This adds a `--inspect`, `-i` option to findjsinstances so that the output of `v8 inspect` is displayed for each instance of a type instead of `v8 print` output. This makes it quicker to view the contents of objects especially where there are few instances of the same kind.
If there's only one instance of `MyObject` then it's easier to type:
```
(llnode) v8 findjsinstances -i MyObject
```
than
```
(llnode) v8 findjsinstances MyObject
0x00002d2fae211241:<Object: MyObject>
(llnode) v8 inspect 0x00002d2fae211241
```
if there's a small number then it's much easier than cut and pasting each hexadecimal reference in turn.
I chose `--inspect` as that matches `v8 inspect` however it could also be `--verbose` and `-v`.
> llscan.cc: Add findjsinstances --verbose option

- src/llnode.cc
- src/llscan.cc
- src/llv8-constants.cc
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
Read values correctly converting for endianess as required.
Generally this just means using LLDB's `ReadUnsignedFromMemory` function but there are a few places where we need optimise reading values and where we only want one byte from a larger field where we need to account for endianess ourselves.
I've tested this with z/Linux core dumps and it enables commands like `v8 findjsobjects`, `findjsinstances` and `v8 inspect` to work. (I've used llnode with these changes to open the z/Linux dumps on my Mac.)
`v8 bt` does not work but that is due to a separate issue with how v8 stacks are implemented on non-x86 systems.
I've verified the tests still pass which confirms these changes don't break little endian support.
> src: Add support for big endian systems

- .gitignore
- scripts/configure.js
Previously if one has `lldb` executable set to something different from what `xcodebuild` integrates, since the plugin will be linked to the default lldb instead of the one loading it, we will get an error when running any llnode commands:
```
error: No valid process, please start something
```
This PR fixes that by detecting the lldb libraries from `llvm-config` first and use that if available. The theory is, if one has a `lldb` different from the default one, then they probably have `llvm-config` setup as well (e.g. `brew install llvm --with-lldb` and configure the PATH to use that version).
Also skip cloning the headers if they are already cloned.
> Try to use the version from llvm-config on MacOS

- README.md
Document that the LLNODE_RANGESFILE environment variable is not needed
with lldb >= 3.9.
> doc: update LLNODE_RANGESFILE documentation

- .travis.yml
- Makefile
- test/common.js
- test/frame-test.js
- test/inspect-test.js
- test/scan-test.js
- test/stack-test.js
- test/usage-test.js
At the moment when a test times out (usually because the expected lldb output does not show up, possible due to an error), there is only a tape timeout message, as is what's happening in our Travis CI build.
This PR checks the timeout and throws an error containing the lldb output for the ease of debugging.
I've tried it on Mac and Linux with v8.9.0 and v6.11.5. I've noticed that the tests are a bit flaky in master, with random timeouts (with this patch on I can see the sent command got swallowed, it's `8 <command>` instead of `v8 <command>` so lldb will error and the test times out). Sometimes there is a ECONNRESET on the pipe. I'll investigate that later.
> test: update travis config, handle errors properly, add TEST_LLNODE_DEBUG

- README.md
I think it's safe to assume most users will want LLDB 3.9 due to #140.
Tested on Ubuntu 16.04.3 LTS (Xenial).
> Switch to LLDB 3.9.

- src/llv8-constants.cc
I'm not sure if we want to note these types of things or not. The JavaScript frame type was removed in https://github.com/v8/v8/commit/c5295b0d71b2024423dbd5c954acd12eceb8f657#diff-a6fe1dc6ffc293ad02ba0491647dfef5.
Even if this doesn't land, I guess this PR is now a record.
> src: add note about remove frame type

- Makefile
- package.json
- src/llnode.cc
- src/llv8-constants.cc
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
Part of my investigation of https://github.com/nodejs/llnode/issues/143, but I think we can get this in first. This helps finding the missing symbols and unknown types so we would know what metadata needs an update .
Refs: https://github.com/nodejs/post-mortem/issues/50
cc @cjihrig @bnoordhuis 
BTW here is the ouput of `LLNODE_CORE=core.inspect.8.9.0 LLNODE_NODE_EXE=node.linux.8.9.0 gmake _travis > /dev/null |& grep llv8 > out.txt` with Node v9.2.0 on MacOS (I used prepared core file and a linux binary to speed up the `scan-test`), the `Unknown HeapObject Type 211` is from my local changes (the `Error` type).
```
[TEST][13193] [stderr] [llv8] Failed to find symbol v8dbg_off_fp_marker
[TEST][13193] [stderr] [llv8] Failed to find symbol v8dbg_class_SharedFunctionInfo__inferred_name__String …
```
> src: improve debug info printed when LLNODE_DEBUG=true

- src/llv8-constants.cc
- test/fixtures/d8-scenario.js
This enables support for loading symbols from shared libraries, e.g. d8 with libv8 and friends.
Below is the debug session in d8 with the simplified d8-scenario.js, I didn't include things like thin strings because some metadata changes needed are floated in node's 6.2 branch.
Tested on macos and ubuntu 16.04 with the d8 built from v8 6.2 branch head. <del>Inspecting the function source  does not work at the moment, but the related symbols loaded are the same as node v9.2, and it seems to be related to https://github.com/nodejs/llnode/issues/138 </del> (It works, but `v8 i -s <function>` doesn't, even though `v8 print <function>` and `v8 source list <function>`  works, see https://github.com/nodejs/llnode/issues/153#issuecomment-348989466) so I think that can be fixed in another PR. …
> src: support loading symbols from shared libraries

- test/common.js
- test/scan-test.js
On linux, lldb 3.9.1 and above returns `lldb version x.x.x` for the `version` command. This patch updates the regexp for version mark in tests.
Fixes: https://github.com/nodejs/llnode/issues/159
> test: fix lldb 3.9+ version separator for linux

- README.md
- doc: add npm badge and use flat square style
- doc: update installation and loading instructions
- Update the prerequisites for each OS, on macOS one can use
brew to install custom versions of lldb, also the shared library
should be installed as well.
- It's no longer necessary to download GYP and lldb headers manually
since the configure scripts would handle all of that
- Mention using `lldbinit` to load the plugin automatically, list
different approaches to load the plugin.
- doc: add section about developing and testing
> docs: update installation, loading, developing and testing instructions

- test/common.js
- test/scan-test.js
This was used by https://github.com/nodejs/llnode/pull/147 to reuse the code that generates a core dump and saves it for testing, but it's worth getting merged first.
cc @cjihrig @bnoordhuis
> test: move core saving and loading into common.js

- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
This is the minimum patch to make llnode display stack traces
produced by v8 6.4.
<details>
<summary>Before</summary>
```
* thread #1: tid = 0x5d87fe, 0x0000000100b5cd02 node`v8::base::OS::Abort() at platform-posix.cc:360, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
* frame #0: 0x0000000100b5cd02 node`v8::base::OS::Abort() at platform-posix.cc:360 [opt]
frame #1: 0x0000000100792d2b node`v8::internal::Runtime_Throw(int, v8::internal::Object**, v8::internal::Isolate*) [inlined] v8::internal::__RT_impl_Runtime_Throw(v8::internal::Arguments, v8::internal::Isolate*) at runtime-internal.cc:71 [opt]
frame #2: 0x0000000100792d0a node`v8::internal::Runtime_Throw(args_length=<unavailable>, args_object=<unavailable>, …
```
> src: fix backtrace with v8 6.4

- src/llnode.cc
- src/llnode.h
- src/llscan.cc
- src/llscan.h
- test/common.js
When the session is created by loading a prepared core dump,
it should delete the target before quitting otherwise the
process will prompt about deleting it and will hang if it
does not receive an answer.
- Eliminates all references to the global llscan in the commands,
only instantiate one LLScan instance in llnode.cc and pass it
down to all commands.
- Eliminates all references to the global llv8, store it inside
the LLScan instead, because LLScan must need a valid llv8
(with postmortem metadata loaded) to function.
- Only instantiate a static LLScan and a static LLV8 during plugin
initialization.
The first commit is a test fix, the second one is spinning off from https://github.com/nodejs/llnode/pull/147 so llscan.o can be linked by another module.
> src: do not create global llscan or global llv8

- .gitignore
- package.json
- scripts/configure.js
- scripts/llnode.sh
Otherwise running `npm link` would always result in unstaged
changes. npm should be able to link the script after installation
is complete and the script has been generated in the module
directory.
Also requires the path module in the generated script so it works
in v4.x.
> scripts: do not check llnode.sh into git

- Makefile
`cleanup.js` now moves ./out/Release/llnode.[so,dylib] to the root of
the project, and the installers were not reflecting this change.
Fixes: https://github.com/nodejs/llnode/issues/173
> build: fix make install-*

- test/inspect-test.js
- Make the test messages more informative.
- Refactor the test flow so that we could skip flaky properties
(currently the potentially neutered typed array)
and that one missing property does not stop later tests.
Refs: https://github.com/nodejs/llnode/issues/150
We should now be able to skip https://github.com/nodejs/llnode/issues/150 , it remains a question whether this should be fixed (or is it fixable?)
<details>
<summary>TAP output of inspect-test.js before this patch</summary>
```
TAP version 13
ok 1 undefined
ok 2 null
ok 3 method should have `this`
ok 4 null
ok 5 addr of `Class` should match
ok 6 null
ok 7 .x smi property
ok 8 .y heap number property
ok 9 .hashmap object property
ok 10 null
ok 11 addr of `Object` should match
ok 12 null
ok 13 [0] null element
ok 14 [4] undefined …
```
> test: refactor inspect-test

- scripts/configure.js
- scripts/darwin.js
- scripts/freebsd.js
- scripts/linux.js
- scripts/lldb.js
This patch refactors all the OS-specific configuration scripts
into separate files:
- `scripts/linux.js` for Linux
- `scripts/darwin.js` for macOS
- `scripts/freebsd.js` for FreeBSD
And put lldb-specific code into `scripts/lldb.js`.
The `scripts/configure.js` now runs a `main()` function
that calls other functions so the configuration code
is now more readable.
Also adds comments in the configuration scripts
and more console outputs during the installation
to help users find issues about their installation.
Tested with the following combinations (with `npm install`):
- macOS 10.12 + Xcode 9.2
- macOS 10.12 + lldb 5.0 (installed with `brew install --with-lldb --with-toolchain llvm`)
- Ubuntu 16.04 + lldb 4.0 (`apt-get install lldb-4.0 liblldb-4.0-dev`)
- FreeBSD 11 + lldb40 (comes with …
> build: refactor os-specific scripts into different files

- src/llscan.cc
- src/llscan.h
- src/llv8-constants.cc
I noticed that we have only a few template strings used in all PrintRefs, and they were repeating multiple times in the code.
> findrefs: refactor ::PrintRefs template strings

- test/scan-test.js
findjsobjects -d test relies on how the hidden-class it tests is built.
Zlib is a builtin from Node.js, therefore we cannot be sure about the
order attributes are assigned to the class, making its hidden-class
unpredictable. Using a class from our fixtures (in this case, Class)
makes the test more predictable across Node.js versions and across
multiple Operating Systems.
Ref: https://github.com/nodejs/llnode/pull/186
> test: more consistent test for findjsobjects -d

- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
V8 6.4 "replaces the in-object properties count byte in the map
with the byte that stores the start offset of in-object properties".
Object inspection on llnode relies on in-object properties being count
bytes, so these are minimal changes to make object inspection work again
with V8 6.4 while keeping compatibility with previous versions.
Ref: https://chromium-review.googlesource.com/c/v8/v8/+/776720
Fixes: https://github.com/nodejs/llnode/issues/158
> src: fix object inspection for V8 6.4

- .travis.yml
- Makefile
- README.md
- test/common.js
* Reworked travis.yaml to use matrix settings, giving us more control
over each job settings.
* Remove v4.x, since it's not a supported release line anymore
* Add jobs v10.x
* Add jobs for Mac OS X
* Add jobs for Node.js master and v8-canary builds. Those jobs are
ignored in the build final result.
* Add a build status table to the README
Ref: https://github.com/nodejs/llnode/issues/187
> travis: increase versions and OS coverage

- src/llnode.cc
- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
ETA: May 29th (or once https://github.com/nodejs/node/pull/19989/ lands)
V8 6.7 unifies SharedFunctionInfo::name and
SharedFunctionInfo::scope_info into
SharedFunctionInfo::name_or_scope_info. Because of that, the function's
name can be inferred either from name_or_scope_info (when it's a string)
or from ScopeInfo::FunctionName (when name_or_scope_info is a
ScopeInfo).
Also, SharedFunctionInfo::GetCode was removed because it wasn't being
used anywhere.
Ref: https://chromium-review.googlesource.com/964201
Fixes: https://github.com/nodejs/llnode/issues/180
> src: fix backtrace for V8 6.7

- binding.gyp
- src/constants.cc
- src/constants.h
- src/error.cc
- src/error.h
- src/llnode.cc
- src/llscan.cc
- src/llscan.h
- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- src/llv8.cc
- src/llv8.h
- src/node-constants.cc
- src/node-constants.h
This commit refactors llv8-constants to make it easier to introduce
Node's internals constants. Common code for llv8 and node constants is
now on src/constants.h. Also moved the Error class to its own file,
removing the dependency on src/llv8.h to use Errors.
> src: add node's internals constants

- src/llnode.cc
- src/llnode.h
- src/llscan.cc
- src/llscan.h
It is referenced in both llnode.cc and llscan.cc,
to make sure targets can compile by only including
llscan.h, this is the minimum change required.
Refs: https://github.com/nodejs/llnode/pull/206
> src: move ParseInspectOptions out of CommandBase

- src/llnode.cc
- src/llscan.cc
- src/llv8-constants.cc
- src/llv8-inl.h
- src/llv8.cc
- src/node-constants.h
Refs: https://github.com/nodejs/llnode/issues/216
The first commit runs clang-format on the src since it's a bit out of sync now.
> src: check oob before slicing String

- .github/workflows/push.yml
coveralls is failing, and codecov seems to be working on actions now, so
replace coveralls with codecov.
> chore(ci): use codecov instead of coveralls

- .github/workflows/push.yml
Refs: https://github.com/nodejs/llnode/issues/362
> chore(ci): temporarily disable OS X

- .github/workflows/push.yml
- COLLABORATOR_GUIDE.md
- CONTRIBUTING.md
- LICENCE.md
- README.md
Signed-off-by: Michael Dawson <mdawson@devrus.com>
> chore: update master -> main

- src/llscan.cc
- src/llv8.cc
- src/llv8.h
- src/printer.cc
Fix various warnings which show up when compiling with gcc. For the most part this doesn't change any semantics -- the only user-facing change is a bug fix in `Printer::Stringify` caused by a missing `return`.
> src: fix warnings

- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
After #404, we no longer support unboxed doubles. Let's remove the relevant code.
> src: remove unboxed double support completely

- src/llv8-constants.cc
- src/llv8-constants.h
- src/llv8-inl.h
- src/llv8.h
- src/printer.cc
This removes ~100 lines of code which were used to support old versions of Node.js. Doing this revealed some more places where we are missing postmortem metadata.
This is best reviewed commit-by-commit.
> remove more code used to support old Node.js versions

- src/llv8-constants.cc
Frankly, this code is currently unused and it probably makes more sense to remove all of it entirely. But if we keep it, let's fix this typo I noticed.
> src: fix PropertyAttributesEnum_DONT_DELETE typo

- src/llv8.cc
This "fixes" the segfault reported in #422, in the sense that you no longer get a segfault. However the printing does not actually work, i.e. you currently get an error like this:
```console
(lldb) v8 i -s 0x2196b1a09a29
error: Invalid source range, start_pos=3108, len=-3098, source_len=10
```
I'm deeming this better than segfaulting. We should really never be segfaulting as the coredump might be incomplete/partially corrupted. (Also, we already know function printing on v16 doesn't work right now.)
> src: don't crash on invalid script positions
